=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'cgi'

module MergeHRISClient
  class CreateLinkTokenApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Creates a link token to be used when linking a new end user.
    # @param link_token [LinkToken] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :production_key The requesting organization&#39;s production key.
    # @return [LinkToken]
    def create_link_token_create(link_token, opts = {})
      data, _status_code, _headers = create_link_token_create_with_http_info(link_token, opts)
      data
    end

    # Creates a link token to be used when linking a new end user.
    # @param link_token [LinkToken] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :production_key The requesting organization&#39;s production key.
    # @return [Array<(LinkToken, Integer, Hash)>] LinkToken data, response status code and response headers
    def create_link_token_create_with_http_info(link_token, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CreateLinkTokenApi.create_link_token_create ...'
      end
      # verify the required parameter 'link_token' is set
      if @api_client.config.client_side_validation && link_token.nil?
        fail ArgumentError, "Missing the required parameter 'link_token' when calling CreateLinkTokenApi.create_link_token_create"
      end
      # resource path
      local_var_path = '/create-link-token'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'production_key'] = opts[:'production_key'] if !opts[:'production_key'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] || @api_client.object_to_http_body(link_token) 

      # return_type
      return_type = opts[:return_type] || 'LinkToken' 

      # auth_names
      auth_names = opts[:auth_names] || ['tokenAuth']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CreateLinkTokenApi#create_link_token_create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
