=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'cgi'

module MergeHRISClient
  class EmploymentsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Returns a list of `Employment` objects.
    # @param x_account_token [String] Token identifying the end user.
    # @param [Hash] opts the optional parameters
    # @option opts [Time] :created_after If provided, will only return objects created after this datetime.
    # @option opts [Time] :created_before If provided, will only return objects created before this datetime.
    # @option opts [String] :cursor The pagination cursor value.
    # @option opts [String] :employee_id If provided, will only return employments for this employee.
    # @option opts [String] :expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
    # @option opts [Boolean] :include_deleted_data Whether to include data that was marked as deleted by third party webhooks.
    # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
    # @option opts [Time] :modified_after If provided, only objects synced by Merge after this date time will be returned.
    # @option opts [Time] :modified_before If provided, only objects synced by Merge before this date time will be returned.
    # @option opts [String] :order_by Overrides the default ordering for this endpoint. Possible values include: effective_date, -effective_date.
    # @option opts [Integer] :page_size Number of results to return per page.
    # @option opts [String] :remote_fields Deprecated. Use show_enum_origins.
    # @option opts [String] :remote_id The API provider&#39;s ID for the given object.
    # @option opts [String] :show_enum_origins Which fields should be returned in non-normalized form.
    # @return [PaginatedEmploymentList]
    def employments_list(x_account_token, opts = {})
      data, _status_code, _headers = employments_list_with_http_info(x_account_token, opts)
      data
    end

    # Returns a list of &#x60;Employment&#x60; objects.
    # @param x_account_token [String] Token identifying the end user.
    # @param [Hash] opts the optional parameters
    # @option opts [Time] :created_after If provided, will only return objects created after this datetime.
    # @option opts [Time] :created_before If provided, will only return objects created before this datetime.
    # @option opts [String] :cursor The pagination cursor value.
    # @option opts [String] :employee_id If provided, will only return employments for this employee.
    # @option opts [String] :expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
    # @option opts [Boolean] :include_deleted_data Whether to include data that was marked as deleted by third party webhooks.
    # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
    # @option opts [Time] :modified_after If provided, only objects synced by Merge after this date time will be returned.
    # @option opts [Time] :modified_before If provided, only objects synced by Merge before this date time will be returned.
    # @option opts [String] :order_by Overrides the default ordering for this endpoint. Possible values include: effective_date, -effective_date.
    # @option opts [Integer] :page_size Number of results to return per page.
    # @option opts [String] :remote_fields Deprecated. Use show_enum_origins.
    # @option opts [String] :remote_id The API provider&#39;s ID for the given object.
    # @option opts [String] :show_enum_origins Which fields should be returned in non-normalized form.
    # @return [Array<(PaginatedEmploymentList, Integer, Hash)>] PaginatedEmploymentList data, response status code and response headers
    def employments_list_with_http_info(x_account_token, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EmploymentsApi.employments_list ...'
      end
      # verify the required parameter 'x_account_token' is set
      if @api_client.config.client_side_validation && x_account_token.nil?
        fail ArgumentError, "Missing the required parameter 'x_account_token' when calling EmploymentsApi.employments_list"
      end
      allowable_values = ["employee", "employee,pay_group", "pay_group"]
      if @api_client.config.client_side_validation && opts[:'expand'] && !allowable_values.include?(opts[:'expand'])
        fail ArgumentError, "invalid value for \"expand\", must be one of #{allowable_values}"
      end
      allowable_values = ["-effective_date", "effective_date"]
      if @api_client.config.client_side_validation && opts[:'order_by'] && !allowable_values.include?(opts[:'order_by'])
        fail ArgumentError, "invalid value for \"order_by\", must be one of #{allowable_values}"
      end
      allowable_values = ["employment_type", "employment_type,flsa_status", "employment_type,flsa_status,pay_frequency", "employment_type,flsa_status,pay_frequency,pay_period", "employment_type,flsa_status,pay_period", "employment_type,pay_frequency", "employment_type,pay_frequency,pay_period", "employment_type,pay_period", "flsa_status", "flsa_status,pay_frequency", "flsa_status,pay_frequency,pay_period", "flsa_status,pay_period", "pay_frequency", "pay_frequency,pay_period", "pay_period"]
      if @api_client.config.client_side_validation && opts[:'remote_fields'] && !allowable_values.include?(opts[:'remote_fields'])
        fail ArgumentError, "invalid value for \"remote_fields\", must be one of #{allowable_values}"
      end
      allowable_values = ["employment_type", "employment_type,flsa_status", "employment_type,flsa_status,pay_frequency", "employment_type,flsa_status,pay_frequency,pay_period", "employment_type,flsa_status,pay_period", "employment_type,pay_frequency", "employment_type,pay_frequency,pay_period", "employment_type,pay_period", "flsa_status", "flsa_status,pay_frequency", "flsa_status,pay_frequency,pay_period", "flsa_status,pay_period", "pay_frequency", "pay_frequency,pay_period", "pay_period"]
      if @api_client.config.client_side_validation && opts[:'show_enum_origins'] && !allowable_values.include?(opts[:'show_enum_origins'])
        fail ArgumentError, "invalid value for \"show_enum_origins\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/employments'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'created_after'] = opts[:'created_after'] if !opts[:'created_after'].nil?
      query_params[:'created_before'] = opts[:'created_before'] if !opts[:'created_before'].nil?
      query_params[:'cursor'] = opts[:'cursor'] if !opts[:'cursor'].nil?
      query_params[:'employee_id'] = opts[:'employee_id'] if !opts[:'employee_id'].nil?
      query_params[:'expand'] = opts[:'expand'] if !opts[:'expand'].nil?
      query_params[:'include_deleted_data'] = opts[:'include_deleted_data'] if !opts[:'include_deleted_data'].nil?
      query_params[:'include_remote_data'] = opts[:'include_remote_data'] if !opts[:'include_remote_data'].nil?
      query_params[:'modified_after'] = opts[:'modified_after'] if !opts[:'modified_after'].nil?
      query_params[:'modified_before'] = opts[:'modified_before'] if !opts[:'modified_before'].nil?
      query_params[:'order_by'] = opts[:'order_by'] if !opts[:'order_by'].nil?
      query_params[:'page_size'] = opts[:'page_size'] if !opts[:'page_size'].nil?
      query_params[:'remote_fields'] = opts[:'remote_fields'] if !opts[:'remote_fields'].nil?
      query_params[:'remote_id'] = opts[:'remote_id'] if !opts[:'remote_id'].nil?
      query_params[:'show_enum_origins'] = opts[:'show_enum_origins'] if !opts[:'show_enum_origins'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      header_params[:'X-Account-Token'] = x_account_token

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'PaginatedEmploymentList'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['tokenAuth']

      new_options = opts.merge(
        :operation => :"EmploymentsApi.employments_list",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EmploymentsApi#employments_list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Returns an `Employment` object with the given `id`.
    # @param x_account_token [String] Token identifying the end user.
    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
    # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
    # @option opts [String] :remote_fields Deprecated. Use show_enum_origins.
    # @option opts [String] :show_enum_origins Which fields should be returned in non-normalized form.
    # @return [Employment]
    def employments_retrieve(x_account_token, id, opts = {})
      data, _status_code, _headers = employments_retrieve_with_http_info(x_account_token, id, opts)
      data
    end

    # Returns an &#x60;Employment&#x60; object with the given &#x60;id&#x60;.
    # @param x_account_token [String] Token identifying the end user.
    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
    # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
    # @option opts [String] :remote_fields Deprecated. Use show_enum_origins.
    # @option opts [String] :show_enum_origins Which fields should be returned in non-normalized form.
    # @return [Array<(Employment, Integer, Hash)>] Employment data, response status code and response headers
    def employments_retrieve_with_http_info(x_account_token, id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EmploymentsApi.employments_retrieve ...'
      end
      # verify the required parameter 'x_account_token' is set
      if @api_client.config.client_side_validation && x_account_token.nil?
        fail ArgumentError, "Missing the required parameter 'x_account_token' when calling EmploymentsApi.employments_retrieve"
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling EmploymentsApi.employments_retrieve"
      end
      allowable_values = ["employee", "employee,pay_group", "pay_group"]
      if @api_client.config.client_side_validation && opts[:'expand'] && !allowable_values.include?(opts[:'expand'])
        fail ArgumentError, "invalid value for \"expand\", must be one of #{allowable_values}"
      end
      allowable_values = ["employment_type", "employment_type,flsa_status", "employment_type,flsa_status,pay_frequency", "employment_type,flsa_status,pay_frequency,pay_period", "employment_type,flsa_status,pay_period", "employment_type,pay_frequency", "employment_type,pay_frequency,pay_period", "employment_type,pay_period", "flsa_status", "flsa_status,pay_frequency", "flsa_status,pay_frequency,pay_period", "flsa_status,pay_period", "pay_frequency", "pay_frequency,pay_period", "pay_period"]
      if @api_client.config.client_side_validation && opts[:'remote_fields'] && !allowable_values.include?(opts[:'remote_fields'])
        fail ArgumentError, "invalid value for \"remote_fields\", must be one of #{allowable_values}"
      end
      allowable_values = ["employment_type", "employment_type,flsa_status", "employment_type,flsa_status,pay_frequency", "employment_type,flsa_status,pay_frequency,pay_period", "employment_type,flsa_status,pay_period", "employment_type,pay_frequency", "employment_type,pay_frequency,pay_period", "employment_type,pay_period", "flsa_status", "flsa_status,pay_frequency", "flsa_status,pay_frequency,pay_period", "flsa_status,pay_period", "pay_frequency", "pay_frequency,pay_period", "pay_period"]
      if @api_client.config.client_side_validation && opts[:'show_enum_origins'] && !allowable_values.include?(opts[:'show_enum_origins'])
        fail ArgumentError, "invalid value for \"show_enum_origins\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/employments/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'expand'] = opts[:'expand'] if !opts[:'expand'].nil?
      query_params[:'include_remote_data'] = opts[:'include_remote_data'] if !opts[:'include_remote_data'].nil?
      query_params[:'remote_fields'] = opts[:'remote_fields'] if !opts[:'remote_fields'].nil?
      query_params[:'show_enum_origins'] = opts[:'show_enum_origins'] if !opts[:'show_enum_origins'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      header_params[:'X-Account-Token'] = x_account_token

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Employment'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['tokenAuth']

      new_options = opts.merge(
        :operation => :"EmploymentsApi.employments_retrieve",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EmploymentsApi#employments_retrieve\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
