=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::EmploymentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EmploymentsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::EmploymentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmploymentsApi' do
    it 'should create an instance of EmploymentsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::EmploymentsApi)
    end
  end

  # unit tests for employments_create
  # Creates an &#x60;Employment&#x60; object with the given values.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @option opts [Employment] :employment 
  # @return [Employment]
  describe 'employments_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for employments_destroy
  # Deletes an &#x60;Employment&#x60; object with the given &#x60;id&#x60;.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @return [AsyncTaskExecution]
  describe 'employments_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for employments_list
  # Returns a list of &#x60;Employment&#x60; objects.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :cursor The pagination cursor value.
  # @option opts [String] :linked_account_id If provided, will only return objects associated with the given &#x60;linked_account_id&#x60;.
  # @option opts [String] :remote_id The API provider&#39;s ID for the given object.
  # @return [PaginatedEmploymentList]
  describe 'employments_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for employments_partial_update
  # Updates an &#x60;Employment&#x60; object with the given &#x60;id&#x60;.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @option opts [PatchedEmployment] :patched_employment 
  # @return [Employment]
  describe 'employments_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for employments_retrieve
  # Returns an &#x60;Employment&#x60; object with the given &#x60;id&#x60;.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Employment]
  describe 'employments_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for employments_update
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Employment] :employment 
  # @return [Employment]
  describe 'employments_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
