=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeHRISClient::FieldMappingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FieldMappingApi' do
  before do
    # run before each test
    @api_instance = MergeHRISClient::FieldMappingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FieldMappingApi' do
    it 'should create an instance of FieldMappingApi' do
      expect(@api_instance).to be_instance_of(MergeHRISClient::FieldMappingApi)
    end
  end

  # unit tests for field_mappings_create
  # Create new Field Mappings that will be available after the next scheduled sync. This will cause the next sync for this Linked Account to sync **ALL** data from start.
  # @param x_account_token Token identifying the end user.
  # @param create_field_mapping_request 
  # @param [Hash] opts the optional parameters
  # @return [FieldMappingInstanceResponse]
  describe 'field_mappings_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for field_mappings_destroy
  # Deletes Field Mappings for a Linked Account. All data related to this Field Mapping will be deleted and these changes will be reflected after the next scheduled sync. This will cause the next sync for this Linked Account to sync **ALL** data from start.
  # @param x_account_token Token identifying the end user.
  # @param field_mapping_id 
  # @param [Hash] opts the optional parameters
  # @return [FieldMappingInstanceResponse]
  describe 'field_mappings_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for field_mappings_partial_update
  # Create or update existing Field Mappings for a Linked Account. Changes will be reflected after the next scheduled sync. This will cause the next sync for this Linked Account to sync **ALL** data from start.
  # @param x_account_token Token identifying the end user.
  # @param field_mapping_id 
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedEditFieldMappingRequest] :patched_edit_field_mapping_request 
  # @return [FieldMappingInstanceResponse]
  describe 'field_mappings_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for field_mappings_retrieve
  # Get all Field Mappings for this Linked Account. Field Mappings are mappings between third-party Remote Fields and user defined Merge fields. [Learn more](https://docs.merge.dev/supplemental-data/field-mappings/overview/).
  # @param x_account_token Token identifying the end user.
  # @param [Hash] opts the optional parameters
  # @return [FieldMappingApiInstanceResponse]
  describe 'field_mappings_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remote_fields_retrieve
  # Get all remote fields for a Linked Account. Remote fields are third-party fields that are accessible after initial sync if remote_data is enabled. You can use remote fields to override existing Merge fields or map a new Merge field. [Learn more](https://docs.merge.dev/supplemental-data/field-mappings/overview/).
  # @param x_account_token Token identifying the end user.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :common_models A comma seperated list of Common Model names. If included, will only return Remote Fields for those Common Models.
  # @option opts [String] :include_example_values If true, will include example values, where available, for remote fields in the 3rd party platform. These examples come from active data from your customers.
  # @return [RemoteFieldAPIResponse]
  describe 'remote_fields_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for target_fields_retrieve
  # Get all organization-wide Target Fields, this will not include any Linked Account specific Target Fields. Organization-wide Target Fields are additional fields appended to the Merge Common Model for all Linked Accounts in a category. [Learn more](https://docs.merge.dev/supplemental-data/field-mappings/target-fields/).
  # @param x_account_token Token identifying the end user.
  # @param [Hash] opts the optional parameters
  # @return [ExternalTargetFieldAPIResponse]
  describe 'target_fields_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
