=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::TasksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TasksApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::TasksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TasksApi' do
    it 'should create an instance of TasksApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::TasksApi)
    end
  end

  # unit tests for tasks_list
  # Returns all &#x60;AsyncTaskExecution&#x60; objects for the requester&#39;s organization.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :cursor The pagination cursor value.
  # @option opts [String] :linked_account_id If provided, will only return objects associated with the given &#x60;linked_account_id&#x60;.
  # @option opts [String] :remote_id The API provider&#39;s ID for the given object.
  # @option opts [String] :status The status of the task.
  # @return [PaginatedAsyncTaskExecutionList]
  describe 'tasks_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tasks_retrieve
  # Returns an &#x60;AsyncTaskExecution&#x60; object with the given &#x60;id&#x60;.
  # @param task_id 
  # @param [Hash] opts the optional parameters
  # @return [AsyncTaskExecution]
  describe 'tasks_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
