=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeHRISClient::CommonModelScopeData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeHRISClient::CommonModelScopeData do
  let(:instance) { MergeHRISClient::CommonModelScopeData.new }

  describe 'test an instance of CommonModelScopeData' do
    it 'should create an instance of CommonModelScopeData' do
      expect(instance).to be_instance_of(MergeHRISClient::CommonModelScopeData)
    end
  end
  describe 'test attribute "common_models"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "linked_account_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
