=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeHRISClient::CommonModelScopes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeHRISClient::CommonModelScopes do
  let(:instance) { MergeHRISClient::CommonModelScopes.new }

  describe 'test an instance of CommonModelScopes' do
    it 'should create an instance of CommonModelScopes' do
      expect(instance).to be_instance_of(MergeHRISClient::CommonModelScopes)
    end
  end
  describe 'test attribute "organization_level_scopes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "scope_overrides"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
