=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeHRISClient::FlsaStatusEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeHRISClient::FlsaStatusEnum do
  let(:instance) { MergeHRISClient::FlsaStatusEnum.new }

  describe 'test an instance of FlsaStatusEnum' do
    it 'should create an instance of FlsaStatusEnum' do
      expect(instance).to be_instance_of(MergeHRISClient::FlsaStatusEnum)
    end
  end
end
