=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeHRISClient::IndividualCommonModelScopeDeserializerRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeHRISClient::IndividualCommonModelScopeDeserializerRequest do
  let(:instance) { MergeHRISClient::IndividualCommonModelScopeDeserializerRequest.new }

  describe 'test an instance of IndividualCommonModelScopeDeserializerRequest' do
    it 'should create an instance of IndividualCommonModelScopeDeserializerRequest' do
      expect(instance).to be_instance_of(MergeHRISClient::IndividualCommonModelScopeDeserializerRequest)
    end
  end
  describe 'test attribute "model_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "model_permissions"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "field_permissions"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
