=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeHRISClient::UnitsEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeHRISClient::UnitsEnum do
  let(:instance) { MergeHRISClient::UnitsEnum.new }

  describe 'test an instance of UnitsEnum' do
    it 'should create an instance of UnitsEnum' do
      expect(instance).to be_instance_of(MergeHRISClient::UnitsEnum)
    end
  end
end
