=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/async_task_execution'
require 'openapi_client/models/async_task_execution_status_enum'
require 'openapi_client/models/benefit'
require 'openapi_client/models/benefit_plan_type_enum'
require 'openapi_client/models/blank_enum'
require 'openapi_client/models/company'
require 'openapi_client/models/country_enum'
require 'openapi_client/models/deduction'
require 'openapi_client/models/document'
require 'openapi_client/models/ein'
require 'openapi_client/models/earning'
require 'openapi_client/models/employee'
require 'openapi_client/models/employee_payroll_run'
require 'openapi_client/models/employment'
require 'openapi_client/models/employment_status_enum'
require 'openapi_client/models/employment_type_enum'
require 'openapi_client/models/ethnicity_enum'
require 'openapi_client/models/flsa_status_enum'
require 'openapi_client/models/gender_enum'
require 'openapi_client/models/hire_date'
require 'openapi_client/models/location'
require 'openapi_client/models/marital_status_enum'
require 'openapi_client/models/null_enum'
require 'openapi_client/models/paginated_async_task_execution_list'
require 'openapi_client/models/paginated_benefit_list'
require 'openapi_client/models/paginated_company_list'
require 'openapi_client/models/paginated_deduction_list'
require 'openapi_client/models/paginated_document_list'
require 'openapi_client/models/paginated_earning_list'
require 'openapi_client/models/paginated_employee_list'
require 'openapi_client/models/paginated_employee_payroll_run_list'
require 'openapi_client/models/paginated_employment_list'
require 'openapi_client/models/paginated_location_list'
require 'openapi_client/models/paginated_payroll_run_list'
require 'openapi_client/models/paginated_report_list'
require 'openapi_client/models/paginated_tax_list'
require 'openapi_client/models/paginated_team_list'
require 'openapi_client/models/paginated_time_off_list'
require 'openapi_client/models/patched_benefit'
require 'openapi_client/models/patched_company'
require 'openapi_client/models/patched_deduction'
require 'openapi_client/models/patched_document'
require 'openapi_client/models/patched_ein'
require 'openapi_client/models/patched_earning'
require 'openapi_client/models/patched_employee'
require 'openapi_client/models/patched_employee_payroll_run'
require 'openapi_client/models/patched_employment'
require 'openapi_client/models/patched_location'
require 'openapi_client/models/patched_payroll_run'
require 'openapi_client/models/patched_report'
require 'openapi_client/models/patched_tax'
require 'openapi_client/models/patched_team'
require 'openapi_client/models/patched_time_off'
require 'openapi_client/models/pay_currency_enum'
require 'openapi_client/models/pay_frequency_enum'
require 'openapi_client/models/pay_period_enum'
require 'openapi_client/models/payroll_run'
require 'openapi_client/models/report'
require 'openapi_client/models/request_type_enum'
require 'openapi_client/models/run_state_enum'
require 'openapi_client/models/run_type_enum'
require 'openapi_client/models/state_enum'
require 'openapi_client/models/tax'
require 'openapi_client/models/team'
require 'openapi_client/models/termination_date'
require 'openapi_client/models/time_off'
require 'openapi_client/models/time_off_status_enum'
require 'openapi_client/models/type_enum'
require 'openapi_client/models/units_enum'

# APIs
require 'openapi_client/api/benefits_api'
require 'openapi_client/api/companies_api'
require 'openapi_client/api/deductions_api'
require 'openapi_client/api/documents_api'
require 'openapi_client/api/earnings_api'
require 'openapi_client/api/employee_payroll_runs_api'
require 'openapi_client/api/employees_api'
require 'openapi_client/api/employments_api'
require 'openapi_client/api/locations_api'
require 'openapi_client/api/payroll_runs_api'
require 'openapi_client/api/reports_api'
require 'openapi_client/api/tasks_api'
require 'openapi_client/api/taxes_api'
require 'openapi_client/api/teams_api'
require 'openapi_client/api/time_off_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
