=begin
#Merge HRIS API

#The unified API for building rich integrations with multiple HR Information System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module MergeHRISClient
  class PayCurrencyEnum
    XUA = "XUA".freeze
    AFN = "AFN".freeze
    DZD = "DZD".freeze
    ARS = "ARS".freeze
    AMD = "AMD".freeze
    AWG = "AWG".freeze
    AUD = "AUD".freeze
    AZN = "AZN".freeze
    BSD = "BSD".freeze
    BHD = "BHD".freeze
    THB = "THB".freeze
    PAB = "PAB".freeze
    BBD = "BBD".freeze
    BYN = "BYN".freeze
    BYR = "BYR".freeze
    BZD = "BZD".freeze
    BMD = "BMD".freeze
    BTN = "BTN".freeze
    VEF = "VEF".freeze
    BOB = "BOB".freeze
    XBA = "XBA".freeze
    BRL = "BRL".freeze
    BND = "BND".freeze
    BGN = "BGN".freeze
    BIF = "BIF".freeze
    XOF = "XOF".freeze
    XAF = "XAF".freeze
    XPF = "XPF".freeze
    CAD = "CAD".freeze
    CVE = "CVE".freeze
    KYD = "KYD".freeze
    CLP = "CLP".freeze
    XTS = "XTS".freeze
    COP = "COP".freeze
    KMF = "KMF".freeze
    CDF = "CDF".freeze
    BAM = "BAM".freeze
    NIO = "NIO".freeze
    CRC = "CRC".freeze
    HRK = "HRK".freeze
    CUP = "CUP".freeze
    CUC = "CUC".freeze
    CZK = "CZK".freeze
    GMD = "GMD".freeze
    DKK = "DKK".freeze
    MKD = "MKD".freeze
    DJF = "DJF".freeze
    STD = "STD".freeze
    DOP = "DOP".freeze
    VND = "VND".freeze
    XCD = "XCD".freeze
    EGP = "EGP".freeze
    SVC = "SVC".freeze
    ETB = "ETB".freeze
    EUR = "EUR".freeze
    XBB = "XBB".freeze
    XBD = "XBD".freeze
    XBC = "XBC".freeze
    FKP = "FKP".freeze
    FJD = "FJD".freeze
    HUF = "HUF".freeze
    GHS = "GHS".freeze
    GIP = "GIP".freeze
    XAU = "XAU".freeze
    XFO = "XFO".freeze
    PYG = "PYG".freeze
    GNF = "GNF".freeze
    GYD = "GYD".freeze
    HTG = "HTG".freeze
    HKD = "HKD".freeze
    UAH = "UAH".freeze
    ISK = "ISK".freeze
    INR = "INR".freeze
    IRR = "IRR".freeze
    IQD = "IQD".freeze
    IMP = "IMP".freeze
    JMD = "JMD".freeze
    JOD = "JOD".freeze
    KES = "KES".freeze
    PGK = "PGK".freeze
    LAK = "LAK".freeze
    KWD = "KWD".freeze
    AOA = "AOA".freeze
    MMK = "MMK".freeze
    GEL = "GEL".freeze
    LVL = "LVL".freeze
    LBP = "LBP".freeze
    ALL = "ALL".freeze
    HNL = "HNL".freeze
    SLL = "SLL".freeze
    LSL = "LSL".freeze
    LRD = "LRD".freeze
    LYD = "LYD".freeze
    SZL = "SZL".freeze
    LTL = "LTL".freeze
    MGA = "MGA".freeze
    MWK = "MWK".freeze
    MYR = "MYR".freeze
    TMM = "TMM".freeze
    MUR = "MUR".freeze
    MZN = "MZN".freeze
    MXV = "MXV".freeze
    MXN = "MXN".freeze
    MDL = "MDL".freeze
    MAD = "MAD".freeze
    BOV = "BOV".freeze
    NGN = "NGN".freeze
    ERN = "ERN".freeze
    NAD = "NAD".freeze
    NPR = "NPR".freeze
    ANG = "ANG".freeze
    ILS = "ILS".freeze
    RON = "RON".freeze
    TWD = "TWD".freeze
    NZD = "NZD".freeze
    KPW = "KPW".freeze
    NOK = "NOK".freeze
    PEN = "PEN".freeze
    MRO = "MRO".freeze
    TOP = "TOP".freeze
    PKR = "PKR".freeze
    XPD = "XPD".freeze
    MOP = "MOP".freeze
    PHP = "PHP".freeze
    XPT = "XPT".freeze
    GBP = "GBP".freeze
    BWP = "BWP".freeze
    QAR = "QAR".freeze
    GTQ = "GTQ".freeze
    ZAR = "ZAR".freeze
    OMR = "OMR".freeze
    KHR = "KHR".freeze
    MVR = "MVR".freeze
    IDR = "IDR".freeze
    RUB = "RUB".freeze
    RWF = "RWF".freeze
    XDR = "XDR".freeze
    SHP = "SHP".freeze
    SAR = "SAR".freeze
    RSD = "RSD".freeze
    SCR = "SCR".freeze
    XAG = "XAG".freeze
    SGD = "SGD".freeze
    SBD = "SBD".freeze
    KGS = "KGS".freeze
    SOS = "SOS".freeze
    TJS = "TJS".freeze
    SSP = "SSP".freeze
    LKR = "LKR".freeze
    XSU = "XSU".freeze
    SDG = "SDG".freeze
    SRD = "SRD".freeze
    SEK = "SEK".freeze
    CHF = "CHF".freeze
    SYP = "SYP".freeze
    BDT = "BDT".freeze
    WST = "WST".freeze
    TZS = "TZS".freeze
    KZT = "KZT".freeze
    XXX = "XXX".freeze
    TTD = "TTD".freeze
    MNT = "MNT".freeze
    TND = "TND".freeze
    TRY = "TRY".freeze
    TMT = "TMT".freeze
    TVD = "TVD".freeze
    AED = "AED".freeze
    XFU = "XFU".freeze
    USD = "USD".freeze
    USN = "USN".freeze
    UGX = "UGX".freeze
    CLF = "CLF".freeze
    COU = "COU".freeze
    UYI = "UYI".freeze
    UYU = "UYU".freeze
    UZS = "UZS".freeze
    VUV = "VUV".freeze
    CHE = "CHE".freeze
    CHW = "CHW".freeze
    KRW = "KRW".freeze
    YER = "YER".freeze
    JPY = "JPY".freeze
    CNY = "CNY".freeze
    ZMK = "ZMK".freeze
    ZMW = "ZMW".freeze
    ZWD = "ZWD".freeze
    ZWN = "ZWN".freeze
    ZWL = "ZWL".freeze
    PLN = "PLN".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PayCurrencyEnum.constants.select { |c| PayCurrencyEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PayCurrencyEnum" if constantValues.empty?
      value
    end
  end
end
