# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [repository_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Runs a single command using the runners shell
      - name: install openapi-generator
        run: |
          python -m pip install --upgrade pip
          pip install openapi-generator

      - name: generate sdk
        run: openapi-generator generate -i http://api.merge.dev/api/hris/v1/schema -g ruby -o . -c config.json

      - uses: EndBug/add-and-commit@v6.1.0
        with:
          author_name: "Dan"
          author_email: "dan@merge.dev"
          message: "Automated SDK Update"
